### ISSUE TITLE
Update project dependencies?

### ISSUE THREAD

**Issue by boxydog** [isaacharrisholt/quiffen#103]
python 3.8 is out of support. See https://devguide.python.org/versions/.

Other dependencies are likely also old. I'm not sure what should be updated, given that it's a library.

You might consider adding a dependabot.yml file for github to remind you of this stuff, although then it would bug you every month, and it wouldn't auto-increment your version.

I might suggest one that looks like the one below, although if you are moving to uv, then poetry is no longer right.

```
# See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates
# and https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```
